# yamllint disable
{{- if not .Values.is_multi_host }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Release.Name }}-hyperdisk-balanced-tpu"
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
  # provisioned-iops: "3000" # Optional: Adjust IOPS as needed
  # provisioned-throughput: "140" # Optional: Adjust Throughput (MiB/s) as needed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-hd-claim"
spec:
  storageClassName: "{{ .Release.Name }}-hyperdisk-balanced-tpu"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.server.data_disk_size}}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-hf-secret"
type: Opaque
stringData:
  hf_api_token: {{.Values.hf_token}}
---
{{- if .Values.gcp_service_account }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k8s_service_account | quote }}
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp_service_account }}
{{- end }}
---
{{- if not .Values.is_multi_host }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-tpu-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tpu-pod"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tpu-pod"
    spec:
      {{- if .Values.gcp_service_account }}
      serviceAccountName: {{ .Values.k8s_service_account | quote }}
      {{- end }}
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu7x
        cloud.google.com/gke-tpu-topology: {{.Values.server.topology}}
      containers:
      - name: vllm-tpu
        image: {{.Values.server.image}}
        command: ["/bin/bash", "-c"]
        args:
        - {{ .Values.server.bash_command | quote }}
        env:
        - name: HF_HOME
          value: /data
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-hf-secret"
              key: hf_api_token
        {{if .Values.server.model_impl_type}}
        - name: MODEL_IMPL_TYPE
          value: {{.Values.server.model_impl_type}}
        {{end}}
        ports:
        - containerPort: 8000
        resources:
          limits:
            google.com/tpu: "{{.Values.server.num_chips_per_node}}"
          requests:
            google.com/tpu: "{{.Values.server.num_chips_per_node}}"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: data-volume
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-hd-claim"
{{- else }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: "{{ .Release.Name }}-tpu-server"
  annotations:
    leaderworkerset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: {{ .Values.server.num_nodes }}
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
          app: "{{ .Release.Name }}-tpu-pod"
      spec:
        {{- if .Values.gcp_service_account }}
        serviceAccountName: {{ .Values.k8s_service_account | quote }}
        {{- end }}
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
          cloud.google.com/gke-tpu-topology: {{.Values.server.topology}}
        containers:
        - name: vllm-leader
          image: {{.Values.server.image}}
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-hf-secret"
                key: hf_api_token
          - name: TPU_MULTIHOST_BACKEND
            value: ray
          - name: TPU_BACKEND_TYPE
            value: jax
          - name: JAX_PLATFORMS
            value: ""
          {{if .Values.server.model_impl_type}}
          - name: MODEL_IMPL_TYPE
            value: {{.Values.server.model_impl_type}}
          {{end}}
          command: ["/bin/bash", "-c"]
          args:
          - {{ .Values.server.bash_command | quote }}
          resources:
            limits:
              google.com/tpu: "{{.Values.server.num_chips_per_node}}"
            requests:
              google.com/tpu: "{{.Values.server.num_chips_per_node}}"
          ports:
          - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
    workerTemplate:
      spec:
        {{- if .Values.gcp_service_account }}
        serviceAccountName: {{ .Values.k8s_service_account | quote }}
        {{- end }}
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
          cloud.google.com/gke-tpu-topology: {{.Values.server.topology}}
        containers:
        - name: vllm-worker
          image: {{.Values.server.image}}
          command:
            - sh
            - -c
            - {{ .Values.server.worker_bash_command | quote }}
          resources:
            limits:
              google.com/tpu: "{{.Values.server.num_chips_per_node}}"
            requests:
              google.com/tpu: "{{.Values.server.num_chips_per_node}}"
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-hf-secret"
                key: hf_api_token
          - name: TPU_MULTIHOST_BACKEND
            value: ray
          - name: TPU_BACKEND_TYPE
            value: jax
          - name: JAX_PLATFORMS
            value: ""
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm

{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-vllm-service"
spec:
  selector:
    app: "{{ .Release.Name }}-tpu-pod"
    {{- if .Values.is_multi_host }}
    role: leader
    {{- end }}
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-client"
spec:
  {{- if .Values.gcp_service_account }}
  serviceAccountName: {{ .Values.k8s_service_account | quote }}
  {{- end }}
  terminationGracePeriodSeconds: 60
  containers:
  - name: vllm-bench
    image: {{.Values.client.image}}
    command: ["/bin/bash", "-c"]
    args: ["{{.Values.client.bash_command}}"]
    env:
    - name: HUGGING_FACE_HUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: hf_api_token
          name: "{{ .Release.Name }}-hf-secret"
    - name: SERVER_HOSTNAME
      value: "{{ .Release.Name }}-vllm-service.default.svc.cluster.local"
  restartPolicy: Never
