"client":
  "bash_command": |-
    while ! curl http://${SERVER_HOSTNAME}:8000/ping; do sleep 30 && echo 'Waiting for server...'; done

    vllm bench serve \
    --dataset-name=random \
    --random-input-len=512 \
    --random-output-len=1024 \
    --num-prompts=1000 \
    --host=${SERVER_HOSTNAME} \
    --port=8000 \
    --model=Qwen/Qwen3-Coder-480B-A35B-Instruct \
    --max-concurrency=64
  "image": |-
    vllm/vllm-tpu:nightly-ironwood-20260224-487a8c1-f91808a
"gcp_service_account": |-
  YOUR_SERVICE_ACCOUNT
"hf_token": !!null |-
  null
"is_multi_host": !!bool |-
  true
"k8s_service_account": |-
  vllm-sa
"server":
  "bash_command": |-
    bash /workspace/vllm/examples/online_serving/multi-node-serving.sh leader --ray_cluster_size=$(LWS_GROUP_SIZE);
    VLLM_DISABLE_SHARED_EXPERTS_STREAM=1 python3 -m vllm.entrypoints.openai.api_server \
    --host=0.0.0.0 \
    --port=8000 \
    --download-dir=/data \
    --tensor-parallel-size=16 \
    --max-model-len=4096 \
    --load-format=runai_streamer \
    --kv-cache-dtype=fp8 \
    --gpu-memory-utilization=0.93 \
    --data-parallel-size=1 \
    --max-num-batched-tokens=2048 \
    --max-num-seqs=512 \
    --model=YOUR_GCS_BUCKET/Qwen3-Coder-480B-A35B-Instruct \
    --served-model-name=Qwen/Qwen3-Coder-480B-A35B-Instruct \
    --no-enable-prefix-caching \
    --no-async-scheduling \
    --enable-expert-parallel
  "data_disk_size": |-
    100Gi
  "image": |-
    vllm/vllm-tpu:nightly-ironwood-20260224-487a8c1-f91808a
  "model_impl_type": |-
    vllm
  "num_chips_per_node": !!int |-
    4
  "num_nodes": !!int |-
    2
  "topology": |-
    2x2x2
  "worker_bash_command": |-
    bash /workspace/vllm/examples/online_serving/multi-node-serving.sh worker --ray_address=$(LWS_LEADER_ADDRESS)
